version: "3"
services:
  django:
    build: .
    ports:
      - 8000:8000
    command: python test_django/manage.py runserver 0.0.0.0:8000
    networks:
      - worknet
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgrespw
    networks:
      - worknet
networks:
  worknet:
